---
ntp_servers:
  - 0.pool.ntp.org
  - 1.pool.ntp.org
  - 2.pool.ntp.org
  - 3.pool.ntp.org
timezone: UTC

name_servers:       
  - 172.16.0.10

hostname: "Ive.finally.got.this.working.com"

bannertxt: "Please Go Aways"

# SMTP Settings
smtp_server: reformMgmtMTA.reform.hmcts.net
local_host_name: dmz.reform.hmcts.net
from_address: dmz@reform.hmcts.net

# iApp Install
as3_url: "https://github.com/F5Networks/f5-appsvcs-extension/releases/download/v3.5.0/f5-appsvcs-3.5.0-3.noarch.rpm"
