---
- name: Install AS3
  bigip_lx_package:
    package: "{{ roles_path }}/{{ package }}"
    provider: "{{ provider }}"
  delegate_to: localhost
  
- name: Enable As3
  bigip_command:
    commands:
      - bash -c '/bin/touch /var/config/rest/iapps/enable'
    provider: "{{ provider }}"
  delegate_to: localhost
