---

- name: Enable Aw3
  bigip_command:
    commands:
      - bash -c '/bin/touch /var/config/rest/iapps/enable'
    provider: "{{ provider }}"
  delegate_to: localhost

- name: Downloads AS3
  get_url:
    url: "{{ as3_url }}"
    dest: /tmp/as3.rpm

- name: Install AS3 rpm
  bigip_lx_package:
    package: /tmp/as3.rpm
    provider:  "{{ provider }}"