---
- name: Wait for BIG-IP to be ready to take configuration
  bigip_wait:
    provider:  "{{ provider }}"
    delay: 5
    timeout: 150
  delegate_to: localhost

- name: Disable the setup utility
  bigip_sys_global:
    gui_setup: no
    banner_text: "{{ bannertxt }}"
    provider:  "{{ provider }}"
  delegate_to: localhost

- name: Set the hostname of the BIG-IP
  bigip_hostname:
    hostname: "{{ hostname }}"
    provider:  "{{ provider }}"
  delegate_to: localhost

- name: Use a file lookup to import PEM Certificate
  bigip_ssl_certificate:
    name: star-platform-hmcts-net
    state: present
    content: "{{ lookup('file', '{{ module_path }}/ansible/star-platform-hmcts-net.crt') }}"
    provider:  "{{ provider }}"
  delegate_to: localhost

- name: Use a file lookup to import key
  bigip_ssl_key:
    name: star-platform-hmcts-net
    state: present
    content: "{{ lookup('file', '{{ module_path }}/ansible/star-platform-hmcts-net.key') }}"
    provider:  "{{ provider }}"
  delegate_to: localhost

- name: Setting Device SSL Setup
  bigip_command:
    commands:
      - "cp /var/config/rest/downloads/star-platform-hmcts-net.crt /config/httpd/conf/ssl.crt/server.crt"
      - "cp /var/config/rest/downloads/star-platform-hmcts-net.key /config/httpd/conf/ssl.key/server.key"
      - tmsh modify /sys httpd ssl-certkeyfile /config/httpd/conf/ssl.key/server.key ssl-certfile /config/httpd/conf/ssl.crt/server.crt
      - tmsh save /sys config partitions all
      #- tmsh restart /sys service httpd
      #- sleep 5    
    provider:  "{{ provider }}"
  delegate_to: localhost
  register: f5_ssl_output

#- debug:
    #var: f5_ssl_output

- name: System Setup
  include_tasks: system.yml

- name: Installing Modules
  include_tasks: modules.yml

- name: Network Setup
  include_tasks: network.yml

- name: Installing AS3 iApp
  include_tasks: as3.yml

- name: Add System Users
  include_tasks: users.yml

#- name: Reboot-BIG-IP
#  bigip_command:
#    commands: tmsh reboot
#    provider:  "{{ provider }}"
#  delegate_to: localhost
