---
- name: Wait for BIG-IP to be ready to take configuration
  bigip_wait:
    provider:  "{{ provider }}"
  delegate_to: localhost

- name: Disable the setup utility
  bigip_sys_global:
    gui_setup: no
    banner_text: "{{ bannertxt }}"
    provider:  "{{ provider }}"
  delegate_to: localhost

- name: Set the hostname of the BIG-IP
  bigip_hostname:
    hostname: "{{ hostname }}"
    provider:  "{{ provider }}"
  delegate_to: localhost

- name: Import Cert Key
  bigip_ssl_key:
    name: star-platform-hmcts-net
    state: present
    content: "{{ lookup('file', 'files/cert.key') }}"
    provider:  "{{ provider }}"
  delegate_to: localhost

- name: Import Cert
  bigip_ssl_certificate:
    name: star-platform-hmcts-net
    state: present
    content: "{{ lookup('file', 'files/cert.pem') }}"
    provider:  "{{ provider }}"
  delegate_to: localhost


- name: System Setup
  include_tasks: system.yml

- name: Network Setup
  include_tasks: network.yml

- name: Installing AS3 iApp
  include_tasks: as3.yml

# Example Node / Pool and Virtual Server Server
#- name: Installing AS3 iApp
# include_tasks: as3.yml
