---
- name: Wait for BIG-IP to be ready to take configuration
  bigip_wait:
    provider:  "{{ provider }}"
  delegate_to: localhost

- name: Disable the setup utility
  bigip_sys_global:
    gui_setup: no
    banner_text: "{{ bannertxt }}"
    provider:  "{{ provider }}"
  delegate_to: localhost
ßß
- name: Set the hostname of the BIG-IP
  bigip_hostname:
    hostname: "{{ hostname }}"
    provider:  "{{ provider }}"
  delegate_to: localhost

#- name: Gen Key
#  shell: |
#    echo -e "n" > /home/vsts/work/1/s/key.txt
#  delegate_to: localhost
#  args:
#    executable: /bin/bash

#- name: OpenSSL Key
#  shell: |
#    ls -al /home/vsts/work/1/s/
#    openssl version -a
#    sudo openssl pkcs12 -in /home/vsts/work/1/s/star-platform-hmcts-net.pfx -out /home/vsts/work/1/s/hmcts_cert.key -nocerts -nodes -passin file:/home/vsts/work/1/s/key.txt
#  delegate_to: localhost
#  args:
#    executable: /bin/bash

#- name: OpenSSL Cert
#  shell: >
#    openssl pkcs12 -in /home/vsts/work/1/s/star-platform-hmcts-net.pfx -out /home/vsts/work/1/s/hmcts_cert.pem -clcerts -nokeys -passin file:key.txt
#  delegate_to: localhost


#- name: Copy Key
#  copy:
#    src: /home/vsts/work/1/s/cert.key
#    dest: /config/ssl/ssl.key
#    provider:  "{{ provider }}"



#- name: Copy Cert
#  copy:
#    src: /home/vsts/work/1/s/cert.crt
#    dest: /config/ssl/ssl.crt/
#    provider:  "{{ provider }}"

- name: System Setup
  include_tasks: system.yml

- name: Network Setup
  include_tasks: network.yml

- name: Installing AS3 iApp
  include_tasks: as3.yml

# Example Node / Pool and Virtual Server Server
#- name: Installing AS3 iApp
# include_tasks: as3.yml


#- name: Setting Device SSL Setup
#  bigip_command:
#    commands:
#      - cp /var/config/rest/downloads/star-platform-hmcts-net.crt /config/httpd/conf/ssl.crt/
#      - cp /var/config/rest/downloads/star-platform-hmcts-net.key /config/httpd/conf/ssl.key/
#      - tmsh modify /sys httpd ssl-certkeyfile /config/httpd/conf/ssl.key/star-platform-hmcts-net.key ssl-certfile /config/httpd/conf/ssl.crt/star-platform-hmcts-net.crt
#      - tmsh save /sys config partitions all
#      - tmsh restart /sys service httpd
#    provider:  "{{ provider }}"
#  delegate_to: localhost
#  run_once: True