---
- name: Set the hostname of the BIG-IP
  bigip_hostname:
    hostname: ansible.did.it.work.com
    provider:  "{{ provider }}"
  delegate_to: localhost

- name: Update password
  bigip_user:
    state: present
    username_credential: admin
    password_credential: admin
    provider: "{{ provider }}"
  delegate_to: localhost

- name: 'f5 | set ntp'
  bigip_device_ntp:
    ntp_servers: "{{ ntp_servers }}"
    provider: "{{ provider }}"
  delegate_to: localhost


- name: Create a base SMTP server configuration
  bigip_smtp:
    name: smtp_reform
    smtp_server: reformMgmtMTA.reform.hmcts.net
    local_host_name: dmz.reform.hmcts.net
    from_address: dmz@reform.hmcts.net
    state: present
    provider: "{{ provider }}"
  delegate_to: localhost