---
- name: Provision ASM Module
  bigip_provision:
    module: asm
    level: nominal
    provider: "{{ provider }}"
  delegate_to: localhost

- name: Import ASM policy
  bigip_asm_policy_import:
    name: asmv131_policy
    source: f5-asm-policy-template-v13/owasp_ready_template/v1/ASMv131/owasp-auto-tune-v131.xml
    provider: "{{ provider }}"
  delegate_to: localhost
