---
- name: Provision ASM Module
  bigip_provision:
    module: asm
    level: nominal
    provider: "{{ provider }}"
  delegate_to: localhost


# - owasp_ready_template/v1/ASMv131/owasp-auto-tune-v131.xml