---

- name: Create VLAN transit
  bigip_vlan:
    name: "{{ vlan_name }}"
    untagged_interface: 1.1
    provider: "{{ provider }}"
  delegate_to: localhost

- name: Create Self IP
  bigip_selfip:
    name: "{{ vlan_name }}"
    address: "{{ self_ip }}"
    netmask: "{{ self_subnet }}"
    vlan: "{{ vlan_name }}"
    provider: "{{ provider }}"
  delegate_to: localhost

- name: Create static default route
  bigip_static_route:
    destination: 0.0.0.0
    netmask: 0.0.0.0
    gateway_address: "{{ default_gateway }}"
    mtu: 1500
    name: internet_out
    provider: "{{ provider }}"
  delegate_to: localhost

- name: Create second static default route
  bigip_static_route:
    destination: 168.63.129.16
    netmask: 255.255.255.255
    gateway_address: "{{ default_gateway }}"
    mtu: 1500
    name: Azure_LB
    provider: "{{ provider }}"
  delegate_to: localhost
