---

- name: Create VLAN transit
  bigip_vlan:
    name: "{{ vlan_name }}"
    untagged_interface: 1.1
    provider: "{{ provider }}"
  delegate_to: localhost

- name: Create Self IP
  bigip_selfip:
    name: "{{ vlan_name }}"
    address: "{{ self_ip }}"
    netmask: "{{ self_subnet }}"
    vlan: "{{ vlan_name }}"
    provider: "{{ provider }}"
  delegate_to: localhost

- name: Create static route to proxy subnet
  bigip_static_route:
    destination: 10.99.73.0
    netmask: 255.255.255.0
    vlan: dmz-transit
    mtu: 1500
    name: inbound_proxy
    provider: "{{ provider }}"
  delegate_to: localhost

- name: Create static default route
  bigip_static_route:
    destination: 0.0.0.0
    netmask: 0.0.0.0
    vlan: dmz-transit
    mtu: 1500
    name: internet_out
    provider: "{{ provider }}"
  delegate_to: localhost