---

- name: Create VLAN transit
  bigip_vlan:
    name: "{{ vlan_name }}"
    untagged_interface: 1.1
    provider: "{{ provider }}"
  delegate_to: localhost

- name: Create Self IP
  bigip_selfip:
    name: "{{ vlan_name }}"
    address: "{{ self_ip }}"
    netmask: "{{ self_subnet }}"
    vlan: "{{ vlan_name }}"
    provider: "{{ provider }}"
  delegate_to: localhost