---
- name: Set the DNS settings on the BIG-IP
  bigip_device_dns:
    name_servers: "{{ name_servers }}"
    search: "{{ dns_search }}"
    provider:  "{{ provider }}"
  delegate_to: localhost

- name: 'f5 | set ntp'
  bigip_device_ntp:
    ntp_servers: "{{ ntp_servers }}"
    timezone: "{{ timezone }}"
    provider: "{{ provider }}"
  delegate_to: localhost


- name: Create a base SMTP server configuration
  bigip_smtp:
    name: smtp_reform
    smtp_server: "{{ smtp_server }}"
    local_host_name: "{{ local_host_name }}"
    from_address: "{{ from_address }}"
    state: present
    provider: "{{ provider }}"
  delegate_to: localhost

- name: Add F5 AS3 user
  bigip_user:
    username_credential: as3_admin
    password_credential: secretpassword
    full_name: as3_admin
    partition_access: all:admin
    update_password: on_create
    state: present
    provider: "{{ provider }}"
  delegate_to: localhost
      